version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: mydb
      MARIADB_USER: 1234
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
volumes:
  mariadb_data:
